// Safe CMS synchronisation. It only creates missing documents/fields and never
// replaces wording that editors have already entered in Sanity.
import {readFileSync} from 'node:fs';

const env = Object.fromEntries(readFileSync(new URL('../.env.local', import.meta.url), 'utf8')
  .split(/\r?\n/).filter(line => line && !line.startsWith('#') && line.includes('='))
  .map(line => { const at = line.indexOf('='); return [line.slice(0, at), line.slice(at + 1).replace(/^"|"$/g, '')] }));

const pages = {
  home: ['Home', '/', {
    heroEyebrow: 'Reading, leadership & lifelong learning', heroTitle: 'Make room for the questions that help us grow.', heroLead: "Dr Santi's Story is a thoughtful platform for families, educators, and leaders who believe books can shape how we grow, care, and lead. Through reflective ideas and meaningful conversation, it nurtures a culture of reading that stays close to everyday life.",
    contextEyebrow: 'A little context', contextTitle: 'Wisdom should feel close enough to use.', contextBodyOne: 'Dr Santi Dharmaputra is a learning and leadership practitioner whose work brings together education, research, executive search, and human development.', contextBodyTwo: "Through reading, stories, and reflective dialogue, she creates room for curiosity, character, and lifelong learning - at home, in schools, and in organizations.", invitationTitle: 'Looking for a more meaningful learning experience?', invitationBody: 'Tell us about the people you are bringing together. We will help identify a format that fits.'
  }],
  about: ['About', '/about', {heroEyebrow: 'About Dr Santi', heroTitle: 'Learning becomes meaningful when it helps us see more clearly.', introOne: 'Dr Santi Dharmaputra is a learning and leadership practitioner with a background spanning education, research, executive search, and leadership development across Indonesia, Australia, and the Netherlands.', introTwo: 'With a PhD in Sociology and Language from the University of Sydney, she brings intellectual curiosity and research into practical conversations about how people learn, grow, and lead.', introThree: "Through Dr Santi's Story, she works with parents, educators, and leaders who want to use reading, stories, and reflective dialogue to build curiosity, character, and lifelong learning.", invitationTitle: 'Bring a thoughtful learning experience to your community.', invitationBody: 'Explore speaking, workshops, and collaborative learning formats.'}],
  programs: ['Programs & Services', '/programs-services', {heroEyebrow: 'For conversations & collaborations', heroTitle: 'A thoughtful starting point for growing a reading culture.', heroLead: 'Perhaps you met Dr Santi at an event, or returned to this card some time later. This page is a lasting place to understand how Dr Santi’s Story works and begin a conversation that fits what you need.', heroNote: 'Dr Santi’s Story is continuing to grow. The formats below are ways to begin today; new services and collaborations will take shape as community needs become clearer.', sectionTitle: 'Choose the conversation that feels most relevant today.', serviceOneTitle: 'Keynote & thoughtful conversations', serviceOneBody: 'A warm, grounded perspective for audiences gathering around reading, learning, parenting, leadership, or human development.', serviceTwoTitle: 'Parent & family workshops', serviceTwoBody: 'Practical spaces for families who want to make reading feel closer to everyday life.', serviceThreeTitle: 'Learning for educators & leaders', serviceThreeBody: 'Reflective sessions for educators and leaders who want to build curiosity, conversation, and a culture of learning.', serviceFourTitle: 'Book conversations & curation', serviceFourBody: 'Book-led conversations and curation direction for communities, reading spaces, book cafés, or libraries that want to grow with intention.', processTitle: 'Every collaboration begins with your context.', stepOneTitle: 'Listen', stepOneBody: 'We begin with the people in the room, what they need, and the change you hope to create.', stepTwoTitle: 'Shape', stepTwoBody: 'We develop a format, perspective, and experience that feels relevant—not a one-size-fits-all package.', stepThreeTitle: 'Continue', stepThreeBody: 'We identify small next steps that people can carry forward after the conversation ends.', invitationTitle: 'Have a need that is not listed yet?', invitationBody: 'Tell us about your context. New services will grow from real conversations with families, schools, communities, and organisations.'}],
  contact: ['Contact', '/contact', {heroEyebrow: 'Contact', heroTitle: 'Start with the people you are bringing together.', heroLead: 'Tell us about your school, community, or organization. We will help identify a learning format that fits.', formEyebrow: 'Start a conversation', formTitle: 'What would you like to make possible?', formLead: 'Share a few details. We aim to respond within 2 working days.'}],
  stories: ['Stories & Resources', '/stories-resources', {heroEyebrow: 'Stories & resources', heroTitle: 'Small ideas that make room for a different kind of attention.', heroLead: 'Perspectives on reading, parenting, learning, and the questions that stay with us.', eventsEyebrow: 'Event archive', eventsTitle: 'Rooms we have shared together.', eventsLead: 'A record of conversations, books, and gatherings that have taken place.'}],
  articles: ['Articles', '/articles', {heroEyebrow: 'Articles', heroTitle: 'Small ideas for a fuller reading life.', heroLead: 'Thoughtful notes on reading, parenting, learning, and the conversations that help them grow.'}],
  'leadership-home': ['Leadership in the Home', '/leadership-in-the-home', {heroEyebrow: 'Leadership in the home', heroTitle: 'Leadership begins long before it has a name.', heroLead: 'At home, children notice how adults listen, make choices, meet uncertainty, and care for other people. Those everyday moments can become an early education in leadership.', introEyebrow: 'A family practice', introTitle: 'Not another task for parents—an invitation to notice what is already happening.', introBodyOne: 'Leadership in the Home is a perspective for families who want to build curiosity, responsibility, reflection, and connection into everyday life. It begins with presence rather than perfection.', introBodyTwo: 'Reading and stories remain part of this work, not as an end in themselves, but as a way to open conversations, imagine other points of view, and practise attention together.', pillarOneTitle: 'Make room for questions', pillarOneBody: 'Use everyday moments, books, and shared experiences to help children wonder, name what matters, and listen to another view.', pillarTwoTitle: 'Let children see repair', pillarTwoBody: 'Leadership includes taking responsibility, apologising, and beginning again. Children learn this by watching it lived.', pillarThreeTitle: 'Practise care together', pillarThreeBody: 'Small choices—how a family speaks, decides, and includes others—become a shared language for empathy and contribution.', invitationTitle: 'Bring this conversation into the rooms where life is being learned.', invitationBody: 'Dr Santi’s Story can shape a conversation, workshop, or learning experience around the questions your community is carrying.'}],
  fantasia: ['Fantasia', '/fantasia', {heroEyebrow: 'Fantasia · 12 September 2026', heroTitle: 'Fantasia', heroLead: 'A small room for stories, imagination, and curiosity.', heroBody: 'Fantasia is a warm gathering by Dr Santi’s Story for families and communities who want to return to books, conversation, and the small possibilities that grow from them.', actionLabel: 'Explore Fantasia documentation'}],
  'fantasia-event': ['Fantasia Event', '/fantasia-event', {heroEyebrow: 'Fantasia · 12 September 2026', heroTitle: 'Reading begins at home.', heroLead: 'A warm parenting session with Fantasia Kindergarten and Preschool on early literacy, shared stories, and the role of parents as a child’s first reading role model.', storyEyebrow: 'A shared conversation', storyTitle: 'Making space for stories from the very beginning.', storyBodyOne: 'At Fantasia, Dr Santi met with parents to explore what literacy can mean in a young child’s everyday life. The session returned to a simple truth: reading habits often begin at home, through the time, language, and attention that parents share with their children.', storyBodyTwo: 'Rather than treating reading as a task to complete, the conversation made room for stories as meaningful quality time—an invitation to be curious together, listen closely, and let books become familiar companions.', themesEyebrow: 'What we explored', themesTitle: 'Three ways stories grow at home.', themesLead: 'Small ideas for making early literacy feel close, meaningful, and shared.', themeOneTitle: 'Early literacy', themeOneBody: 'How children meet language, pictures, stories, and books long before reading feels like a skill.', themeTwoTitle: 'Parents as role models', themeTwoBody: 'How everyday acts of reading can show children that books have a place in family life.', themeThreeTitle: 'Quality time', themeThreeBody: 'How shared reading can become a gentle moment of attention, conversation, and connection.'}],
  cartea: ['Cartea Event', '/stories-resources/cartea', {heroEyebrow: 'Cartea x Dr Santi’s Story', heroTitle: 'Cartea', heroLead: 'Reading culture across generations—with around 50 people who came to listen, question, and share their experiences.', storyTitle: 'A room to read, question, and connect.'}],
  partnership: ['Partnership', '/partnership', {heroEyebrow: 'Partnership', heroTitle: 'A library is more than a collection. It is an everyday invitation.', heroLead: "Dr Santi's Story partners with homes, schools, and workplaces to shape thoughtful reading environments—starting from the people who will use them.", invitationTitle: 'Tell us about the library you want to bring to life.', invitationBody: 'Partnership formats, scope, and fees are developed after an initial conversation.'}],
  collaborate: ['Collaborate', '/collaborate', {heroEyebrow: 'Let’s collaborate', heroTitle: 'Let’s make room for reading, learning, and growth.', heroLead: 'Thank you for stopping by. Dr Santi’s Story begins conversations with families, schools, communities, and organisations that want books and learning to feel more alive in everyday life.', audiencesTitle: 'Every collaboration begins with your context.', audienceOneTitle: 'Schools & institutions', audienceOneBody: 'Sessions, programmes, and learning perspectives shaped around the people within them.', audienceTwoTitle: 'Families & communities', audienceTwoBody: 'Spaces for making reading, conversation, and curiosity part of life together.', audienceThreeTitle: 'Teams & organisations', audienceThreeBody: 'Reflective conversations on leadership, learning culture, and human development.', invitationTitle: 'One good conversation can open many possibilities.', invitationBody: 'Tell us who you hope to gather, what you are facing, and the possibility you want to open. We will help find the right starting point.'}],
  'speaking-collaboration': ['Speaking & Collaboration', '/speaking-collaboration', {heroEyebrow: 'Speaking & collaboration', heroTitle: 'Bring a more meaningful learning conversation to your community.', heroLead: 'Thoughtful experiences for parents, educators, schools, and organizations who want to make reading, reflection, and lifelong learning part of everyday life.', quote: '“The most meaningful learning does not simply give us answers. It makes us ask better questions.”'}]
};

const label = key => key.replace(/([A-Z])/g, ' $1').replace(/^./, character => character.toUpperCase());
const asFields = values => Object.entries(values).map(([key, value]) => ({_key: key, _type: 'copyField', key, label: label(key), value}));
const endpoint = `https://${env.SANITY_API_PROJECT_ID}.api.sanity.io/v2025-02-19/data`;
const query = encodeURIComponent('*[_id in $ids]{_id,_rev,title,pageId,previewUrl,seoDescription,fields}');
const ids = Object.keys(pages).flatMap(id => [`pageCopy.${id}`, `drafts.pageCopy.${id}`]);
const response = await fetch(`${endpoint}/query/${env.SANITY_API_DATASET}?query=${query}&$ids=${encodeURIComponent(JSON.stringify(ids))}`, {headers: {Authorization: `Bearer ${env.SANITY_API_WRITE_TOKEN}`}});
if (!response.ok) throw new Error((await response.text()) || 'Could not read existing CMS content.');
const existing = new Map((await response.json()).result.map(document => [document._id, document]));
const mutations = [];

for (const [id, [title, path, values]] of Object.entries(pages)) {
  const documentId = `pageCopy.${id}`;
  const current = existing.get(documentId);
  if (!current) {
    mutations.push({createIfNotExists: {_id: documentId, _type: 'pageCopy', title, pageId: id, previewUrl: `https://www.drsantistory.com${path}`, fields: asFields(values)}});
    continue;
  }
  const keys = new Set((current.fields || []).map(field => field.key));
  const missing = asFields(Object.fromEntries(Object.entries(values).filter(([key]) => !keys.has(key))));
  if (missing.length) mutations.push({patch: {id: documentId, ifRevisionID: current._rev, set: {fields: [...(current.fields || []), ...missing]}}});
}

if (!mutations.length) {
  console.log('CMS is already synchronised; no existing wording was changed.');
} else {
  const mutationResponse = await fetch(`${endpoint}/mutate/${env.SANITY_API_DATASET}`, {method: 'POST', headers: {Authorization: `Bearer ${env.SANITY_API_WRITE_TOKEN}`, 'Content-Type': 'application/json'}, body: JSON.stringify({mutations})});
  if (!mutationResponse.ok) throw new Error((await mutationResponse.text()) || 'Could not synchronise CMS content.');
  console.log(`Safely synchronised ${mutations.length} CMS document update(s).`);
}
